name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vibe-code-ui

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Zip Build Output
        run: zip -r release.zip ./dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-frontend
          path: release.zip

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: vite-frontend

      - name: Unzip Artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VibeCodeFrontend'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: ./dist
